// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq0tlKmlHGneuOuBXqKHKg2cQL1geX10w',
    appId: '1:1035147059079:web:df73bcddca5c745b2f3d22',
    messagingSenderId: '1035147059079',
    projectId: 'chatapp-9cb89',
    authDomain: 'chatapp-9cb89.firebaseapp.com',
    storageBucket: 'chatapp-9cb89.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx12PL4fI_k7-w0uBoSw7i8SydwMtiGn0',
    appId: '1:1035147059079:android:4fe3a8e6336a47d72f3d22',
    messagingSenderId: '1035147059079',
    projectId: 'chatapp-9cb89',
    storageBucket: 'chatapp-9cb89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8SAtk2hCcDS1lB7pBkhR7erZhnx535JU',
    appId: '1:1035147059079:ios:7817cbdb413163282f3d22',
    messagingSenderId: '1035147059079',
    projectId: 'chatapp-9cb89',
    storageBucket: 'chatapp-9cb89.appspot.com',
    iosClientId: '1035147059079-ioljpahhf7f4cod71jfevm7edge7rote.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8SAtk2hCcDS1lB7pBkhR7erZhnx535JU',
    appId: '1:1035147059079:ios:7817cbdb413163282f3d22',
    messagingSenderId: '1035147059079',
    projectId: 'chatapp-9cb89',
    storageBucket: 'chatapp-9cb89.appspot.com',
    iosClientId: '1035147059079-ioljpahhf7f4cod71jfevm7edge7rote.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapplication',
  );
}
